addSbtPlugin("com.github.sbt"    % "sbt-dynver"          % "5.1.0")
addSbtPlugin("com.github.sbt"    % "sbt-native-packager" % "1.11.1")
addSbtPlugin("org.scoverage"     % "sbt-scoverage"       % "2.3.1")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"        % "2.5.4")
addSbtPlugin("nl.gn0s1s"        %% "sbt-dotenv"          % "3.1.1")
addSbtPlugin("ch.epfl.scala"     % "sbt-scalafix"        % "0.14.0")
addSbtPlugin("com.github.sbt"    % "sbt-javaagent"       % "0.1.8")
addSbtPlugin("de.heikoseeberger" % "sbt-header"          % "5.10.0")
